In [1]:
import torch

### PyTorch is same as NumPy

In [12]:
x = torch.arange(12)

In [13]:
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [14]:
x.shape

torch.Size([12])

In [15]:
x.numel()

12

In [17]:
x.reshape(3,4)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [19]:
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [20]:
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

### Use Python list to create 2-Dimension 

In [25]:
torch.tensor([[1,2,3,4], [5,6,7,8], [9,10,11,12]]).shape

torch.Size([3, 4])

In [24]:
torch.tensor([[[1,2,3,4], [5,6,7,8], [9,10,11,12]]]).shape

torch.Size([1, 3, 4])

###  Fundament Operation

In [36]:
x = torch.tensor([1.0, 2, 5, 8])  # 1.0 can change the operation from int to float
y = torch.tensor([2, 2, 2, 2])  
x+y, x-y, x*y, x/y, x**y  # ** means index operation

(tensor([ 3.,  4.,  7., 10.]),
 tensor([-1.,  0.,  3.,  6.]),
 tensor([ 2.,  4., 10., 16.]),
 tensor([0.5000, 1.0000, 2.5000, 4.0000]),
 tensor([ 1.,  4., 25., 64.]))

In [37]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 1.4841e+02, 2.9810e+03])

In [38]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X, Y), axis=0), torch.cat((X, Y), axis=1)  # axis=0 vertical(cow direction), axis=1 horizontal(column direction)
# torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)  # dim=0 vertical(cow direction), dim=1 horizontal(column direction)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

#### Logical Operation

In [39]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [40]:
X.sum()

tensor(66.)

#### Broadcasting Mechanism 

In [42]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [43]:
a + b  # copy the elements of a and b to (3, 2)

tensor([[0, 1],
        [1, 2],
        [2, 3]])

#### Index and Slice

In [44]:
X[-1], X[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [46]:
X[1, 2] = 99
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5., 99.,  7.],
        [ 8.,  9., 10., 11.]])

In [48]:
X[0:2, : ] = 30
X

tensor([[30., 30., 30., 30.],
        [30., 30., 30., 30.],
        [ 8.,  9., 10., 11.]])

#### Save memory

In [51]:
before = id(Y)  # get the memory address of Y
Y = Y+X
id(Y) == before

False

In [57]:
Z = torch.zeros_like(Y)  # create a zero array and its shape is Y
print("id(Z):", id(Z))
Z[ : ] = X+Y  # all elements of Z = X+Y
print('id(Z):', id(Z))

id(Z): 1400717995176
id(Z): 1400717995176


In [58]:
before = id(Y)  # get the memory address of Y
X += Y
id(Y) == before

True

###  From NumPy to PyTorch

In [60]:
A = X.numpy()
B = torch.tensor(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [61]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)