In [19]:
import torch

tensor([0., 1., 2., 3.])

### Simple example of 2 scalars 

In [ ]:
x = torch.arange(4.0)
x

In [20]:
x.requires_grad_(True)   # Same as `x = torch.arange(4.0, requires_grad=True)
print(x.grad) # defalut is None

None


In [ ]:
# y = 2 * torch.dot(x, x)
y

In [22]:
y.backward()
print(x.grad)

tensor([ 0.,  4.,  8., 12.])


In [23]:
x.grad == 4 * x

tensor([True, True, True, True])

In [24]:
x.grad.zero_()  # Gradient reset to zero

y = x.sum()
y.backward()
print(x.grad)

tensor([1., 1., 1., 1.])


### Backward for non-scalar varibles——get sum and back prop

In [26]:
x.grad.zero_()  # Gradient reset to zero

y = x * x
y.sum().backward()  # In DL, we often use scalar to propagate backward.   So we get the sum first
print(x.grad)  

tensor([0., 2., 4., 6.])


### Move computation out of the computation graph

In [31]:
x.grad.zero_()  # Gradient reset to zero

y = x * x
u = y.detach()
z = u*x

z.sum().backward()
print(x.grad == u)  # Now python think u is just like a constant number 

tensor([True, True, True, True])


In [32]:
x.grad.zero_()  # Gradient reset to zero

y.sum().backward()
print(x.grad == 2 * x)

tensor([True, True, True, True])


### Compute the gradient of Python control flow (e.g. if, loops, etc)

In [34]:
def f(a):
    b = a * 2
    while b.norm()<1000:
        b = b * 2
    if b.sum() > 0:
        c = b
    else:
        c = 100 * b
    return c

a = torch.randn(size=(), requires_grad=True)  # size=() means it is a scalar
d = f(a)
d.backward()

a.grad == d / a

tensor(True)