In [2]:
import torch
import torch.nn.functional as F
from torch import nn

tensor([-2., -1.,  0.,  1.,  2.])

### Customize a Layer

In [3]:
class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()
        
    def forward(self, X):
        return X - X.mean()
    
layer = CenteredLayer()
layer(torch.FloatTensor([1,2,3,4,5]))

tensor([-2., -1.,  0.,  1.,  2.])

In [4]:
net = nn.Sequential(nn.Linear(8, 128), CenteredLayer())

Y = net(torch.rand(4, 8))
Y.mean()

tensor(-4.6566e-10, grad_fn=<MeanBackward0>)

### Customize a Layer with Various Parameters

In [6]:
# nn.Parameters to zip the values we initialize
class MyLinear(nn.Module):
    def __init__(self, in_units, units):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_units, units))  
                    # put the random uniform distribution from -1 to 1 into the nn.Parameter function 
                    # can give all values gradients and names
        self.bias = nn.Parameter(torch.zeros(units,))
        
    def forward(self, X):
        linear = torch.matmul(X, self.weight.data) + self.bias.data  
                # .mm only for 2D matrix multiplication; .matmul can for all dimension
        return F.relu(linear)
    
dense = MyLinear(5, 3)
dense.weight

Parameter containing:
tensor([[-1.1969,  0.2078,  0.6029],
        [ 1.5298,  0.5604,  0.2543],
        [ 0.2170, -0.2082, -0.3595],
        [-0.6348,  0.8626, -1.4324],
        [ 0.0209,  0.7861, -0.7824]], requires_grad=True)

In [7]:
dense(torch.rand(2, 5))

tensor([[0.0000, 0.8641, 0.0000],
        [0.0000, 1.9377, 0.0000]])

In [8]:
net = nn.Sequential(MyLinear(64, 8), MyLinear(8, 1))
net(torch.rand(2, 64))

tensor([[1.1769],
        [4.9426]])